Write a Bash script that transfers a file from our client to a server:

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -14,4 +14,11 @@ USERNAME=$3
 PATH_TO_SSH_KEY=$4
 
 # Transfer the file using scp with strict host key checking disabled
-scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"
+scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$SERVER_IP:~/"
+
+# Check if the scp command was successful
+if [ $? -eq 0 ]; then
+  echo "File transferred successfully."
+else
+  echo "File transfer failed."
+fi
