0. Double the number of webservers

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,9 +1,5 @@
 #!/usr/bin/env bash
-# This script installs and configures Nginx to have a custom 404 page
-# that contains the string "Ceci n'est pas une page."
-
-# Exit immediately if a command exits with a non-zero status
-set -e
+# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
 
 # Check if nginx is installed
 if [ ! -e /usr/sbin/nginx ]; then
@@ -15,39 +11,43 @@ else
 fi
 
 # Ensure that the directory is present.
-if [ ! -e /var/www/html ]; then
+if [ ! -d /var/www/html ]; then
     mkdir -p /var/www/html
 fi
 
-# Prepare the custom file
+# Prepare the custom files
 echo "Ceci n'est pas une page" > /var/www/html/404.html
-echo "Hello World!" > /var/www/html/index.html
+echo 'Hello World!' > /var/www/html/index.html
 
-# Configure Nginx
-cat <<EOF > /etc/nginx/sites-available/default
+# Create the Nginx configuration
+cat << EOF > /etc/nginx/sites-available/default
 server {
     listen 80 default_server;
     listen [::]:80 default_server;
-    add_header X-Served-By $HOSTNAME;
-
+    add_header X-Served-By \$HOSTNAME;
     root /var/www/html;
-
-    location / {
-        try_files \$uri \$uri/ =404;
-    }
+    index index.html index.htm;
 
     location /redirect_me {
         return 301 https://youtube.com/;
     }
 
     error_page 404 /404.html;
-
     location = /404.html {
         internal;
+    }
+
+    location / {
+        try_files \$uri \$uri/ =404;
     }
 }
 EOF
 
-# Restart Nginx to apply the changes
-service nginx restart
-echo "Nginx configured with custom 404 page successfully."
+# Test the Nginx configuration
+if nginx -t; then
+    systemctl restart nginx
+    echo "Nginx configured with custom 404 page successfully."
+else
+    echo "Nginx configuration test failed. Please check your configuration."
+    exit 1
+fi
